### ISSUE TITLE
Active Directory Instructions Update

### ISSUE THREAD

**Issue by dperryazauditor** [azauditor/ADAudit#1]
Step 1: Click the green 'Clone or download' button above to download the ZIP file of the repository.

**Comment by aentringer** [comment]
Danielle, why would an individual require a full clone/download of the repository? The current instructions inform the user to right-click save-as the preceding link, which directly downloads the formatted PowerShell script. Are these instructions not clear?

**Comment by dperryazauditor** [comment]
Hi Alex, we’ve found that IT Directors at school districts commonly run into problems by following these instructions. They right-click the “PowerShell’ Folder” and end up saving the .html file or correctly right-click and save the Get-AuditData.ps1 but get an error similar to this when running the file (this is just a snippet, let me know if you’d like to see the full error we were sent):
At C:\Get-ADAuditData.ps1:185 char:102
+ ... light text-normal text-mono f5 mb-2  border-top pt-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Get-ADAuditData.ps1:218 char:185
+ ... r" data-ga-click="(Logged out) Header, go to Pricing">Plans <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

I’m not entirely sure what this error means but my thought process was the .ps1 file was missing something that is contained in the ZIP and we’ve found that when having them download the ZIP and then running the .ps1 file from the ZIP they stop seeing this sort of redirection error.

Please let me know if you know of a different work around for these types of errors and maybe we don’t need to change the instructions.

**Comment by aentringer** [comment]
Instructions have been clarified for end users.
